services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: properli
      POSTGRES_PASSWORD: properli
      POSTGRES_DB: properli
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
